[20:06:12.614] Running build in Washington, D.C., USA (East) â€“ iad1
[20:06:12.724] Cloning github.com/rlim99/SmartGrocery (Branch: main, Commit: efd13a5)
[20:06:13.069] Cloning completed: 345.000ms
[20:06:13.306] Restored build cache from previous deployment (G14ZbtfB74uFgJYibqCWcczK6j8R)
[20:06:13.385] Running "vercel build"
[20:06:13.775] Vercel CLI 41.1.3
[20:06:13.886] WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
[20:06:13.909] Installing required dependencies...
[20:06:20.961] Build Completed in /vercel/output [7s]
[20:06:21.179] Deploying outputs...
[20:06:38.801] 
[20:06:39.093] Deployment completed
[20:06:40.178] Uploading build cache [29.00 B]...
[20:06:40.265] Build cache uploaded: 87.154ms
=============================================================
Traceback (most recent call last):
File "/var/task/vc__handler__python.py", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/var/task/app.py", line 10, in <module>
from barcode_functions import capture_image, recognize_barcode, recognize_item, count_quantity_from_image
File "/var/task/barcode_functions.py", line 6, in <module>
from image_processing import process_image
File "/var/task/image_processing.py", line 6, in <module>
import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File "/var/task/vc__handler__python.py", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/var/task/app.py", line 10, in <module>
from barcode_functions import capture_image, recognize_barcode, recognize_item, count_quantity_from_image
File "/var/task/barcode_functions.py", line 6, in <module>
from image_processing import process_image
File "/var/task/image_processing.py", line 6, in <module>
import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
===========================================================================
Traceback (most recent call last):
File "/var/task/vc__handler__python.py", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/var/task/app.py", line 10, in <module>
from barcode_functions import capture_image, recognize_barcode, recognize_item, count_quantity_from_image
File "/var/task/barcode_functions.py", line 6, in <module>
from image_processing import process_image
File "/var/task/image_processing.py", line 6, in <module>
import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File "/var/task/vc__handler__python.py", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/var/task/app.py", line 10, in <module>
from barcode_functions import capture_image, recognize_barcode, recognize_item, count_quantity_from_image
File "/var/task/barcode_functions.py", line 6, in <module>
from image_processing import process_image
File "/var/task/image_processing.py", line 6, in <module>
import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Python process exited with exit status: 1. The logs above can help with debugging the issue.